stages:
  - test
  - docs

# Change pip's cache directory to be inside the project directory since we can only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip
    
    
.anabrid-poetry-job:
  image:
    name: $CI_REGISTRY/pybrid-computing/pybrid-computing-base/python-poetry
  before_script:
    # Store user/password info in ~/.netrc, which will be automatically used by poetry
    - echo "machine ${ANABRID_PYTHON_INDEX_HOST:?CI variable missing}" > $HOME/.netrc
    - echo "login ${ANABRID_PYTHON_INDEX_USER:?CI variable missing}" >> $HOME/.netrc
    - echo "password ${ANABRID_PYTHON_INDEX_PASSWORD:?CI variable missing}" >> $HOME/.netrc


test_job:
  extends: .anabrid-poetry-job
  stage: test
  script:
    - poetry --no-interaction install --sync --with dev
    - poetry --no-interaction run pytest


docs_job:
  extends: .anabrid-poetry-job
  image:
    name: $CI_REGISTRY/pybrid-computing/pybrid-computing/sphinx-build
  stage: docs
  script:
    - poetry --no-interaction install --sync --with dev
    # Build documentation with warnings treated as errors (-W)
    # Care: -M html <src> <dest> must come first
    - poetry run sphinx-build -M html docs/ docs/_build/html/ -W --keep-going
  artifacts:
    paths:
      - docs/_build/html
    expire_in: 1 month
