# Copyright (c) 2022-2024 anabrid GmbH
# Contact: https://www.anabrid.com/licensing/
# SPDX-License-Identifier: MIT OR GPL-2.0-or-later

from pathlib import Path as FilePath

from pybrid.redac import REDAC

# Import a computer hardware structure from a previous export.
# This export was generated by running `pybrid redac display --export redac-0.json`
source = FilePath(__file__).parent / "redac-0.json"
computer = REDAC.create_from(source)

# You can configure arbitrary parts of the computer offline
for carrier in computer.carriers:
    for cluster in carrier.clusters:
        # Configure harmonic oscillator
        cluster.route(0, 0, -1.0, 1)
        cluster.route(1, 1, 1.0, 0)
        cluster.m0block.elements[0].ic = 0.42
        # Configure which signals you want to capture
        computer.daq.capture(cluster.m0block.elements[0], cluster.m0block.elements[1])

# Export PB configuration for later use, either `pybrid redac run -c sinusoidal-circuit.json` or redaccess
config = computer.to_pb()
target = FilePath(__file__).parent / "redac-0-configuration.json"
with open(target, "w") as f:
    for c in config:
        f.write(str(c) + "\n")
