# Copyright (c) 2022-2024 anabrid GmbH
# Contact: https://www.anabrid.com/licensing/
# SPDX-License-Identifier: MIT OR GPL-2.0-or-later

from pybrid.redac import REDAC, Path

# Import a computer hardware structure from a previous export.
# This export was generated by running `pybrid redac display --export redac-0.json`
computer = REDAC.create_from(
    "/home/steck/anabrid/lucidac/firmware/hybrid-controller/test/manual/redac/test_inter_mredac_calibration_syncronization/computer.json"
)
router = computer.router
# TODO: Fix REDAC constructor
for carrier in computer.carriers:
    router.add_carrier(carrier)

# One sinusoidal inside each cluster
for carrier in computer.carriers:
    for cluster in carrier.clusters:
        # Configure harmonic oscillator
        cluster.route(0, 0, -1.0, 1)
        cluster.route(1, 1, 1.0, 0)
        # Configure initial value
        cluster.m0block.elements[0].ic = 0.42

        # Configure which signals you want to capture
        computer.daq.capture(cluster.m0block.elements[0])

# One sinusoidal spanning cluster 0-1
for idx, carrier in enumerate(computer.carriers):
    # Route sinusoidal between two clusters on the same carrier
    cluster_a, cluster_b = carrier.clusters[0:2]

    # First integrator to second integrator
    cluster_a.m0block.elements[2].ic = -0.2 - idx * 0.01
    cluster_a.ublock.connect(2, 8)
    cluster_a.cblock.elements[8].factor = -1.0
    router.route(carrier.tblock.loc() / 0 / 8, carrier.tblock.loc() / 1 / 8)
    cluster_b.iblock.connect(8, 2)

    # Second integrator back to first
    cluster_b.ublock.connect(2, 9)
    cluster_b.cblock.elements[9].factor = 1.0
    router.route(carrier.tblock.loc() / 1 / 9, carrier.tblock.loc() / 0 / 9)
    cluster_a.iblock.connect(9, 2)

    # Capture data
    computer.daq.capture(cluster_a.m0block.elements[2], cluster_b.m0block.elements[2])

# One sinusoidal spanning m0.cl0-m2.cl0
i0_m0, i0_m2 = (
    computer.get_entity(Path.parse("00-00-00-00-00-00")),
    computer.get_entity(Path.parse("00-00-00-00-00-02")),
)
# We use the first cluster on both carriers
i0_m0_cl0, i1_m0_cl0 = i0_m0.clusters[0], i0_m2.clusters[0]

# First integrator from iREDAC0 to iREDAC1
i0_m0_cl0.m0block.elements[4].ic = -0.82
i0_m0_cl0.ublock.connect(4, 31)
i0_m0_cl0.cblock.elements[31].factor = -1.0
router.route(i0_m0.tblock.loc() / 0 / 31, i0_m2.tblock.loc() / 0 / 31)
i1_m0_cl0.iblock.connect(31, 4)

# Second integrator from iREDAC1 to iREDAC0
i1_m0_cl0.m0block.elements[4].ic = 0
i1_m0_cl0.ublock.connect(4, 16)
i1_m0_cl0.cblock.elements[16].factor = 1.0
router.route(i0_m2.tblock.loc() / 0 / 16, i0_m0.tblock.loc() / 0 / 16)
i0_m0_cl0.iblock.connect(16, 4)

computer.daq.capture(i0_m0_cl0.m0block.elements[4], i1_m0_cl0.m0block.elements[4])

# Export JSON configuration for later use, either `pybrid redac run -c sinusoidal-circuit.json` or redaccess
i0_m0.path = Path(("04-E9-E5-18-14-84", *i0_m0.path[1:]))
i0_m2.path = Path(("04-E9-E5-18-14-83", *i0_m2.path[1:]))
#i0_m2.path = Path(("04-E9-E5-18-16-43", *i0_m2.path[1:]))
with open(
    "/home/steck/anabrid/lucidac/firmware/hybrid-controller/test/manual/redac/test_inter_mredac_calibration_syncronization/config.h",
    "w",
) as target:
    target.write('const char* json_config = R"json(\n')
    target.write(computer.dumps(sort_keys=True))
    target.write('\n)json";\n')
